### PR TITLE
revamp XML parsing, ESLint, many other tweaks

### PR DESCRIPTION
**Pull request by derhuerst**
First of all: Thanks for writing this client!

As part of a project, I'm currently adapting `trias-client` in order to pull fares/tickets data from a TRIAS endpoint. While experimenting with different TRIAS endpoints, I made changes that I want to contribute now.

Unfortunately, that process has made this PR a monster, containing many unrelated commits. *If* you want to review it, I advise you to do it per-commit, each commit should be well-scoped and atomic; If you don't want to review this, I'm fine with breaking it up into more focused PRs, just let me know!

**This PR mainly prepares the code base for further extensions. It also adds one tiny feature: fares/tickets parsing.**

Some comments on the changes:

- d7c0f05 This allows subsequent code (and the TypeScript type checker) to assume that `payload` is not empty/`undefined`.
- c2dbeb5 Adding an environment-variable-based debug hook allows people to debug their `trias-client`-based systems without fiddling with the code. The same mechanism has helped me provide support for `hafas-client` many times.
- f3d0f63 TSLint is deprecated, so I switched to ESLint.
- 285a8a4 I verified that the ticket parsing works with the VRN TRIAS endpoint.
- f6b2f66 Using `async`/`await` makes the code more readable and stack traces more actionable.
- fb19b58 I didn't necessarily move away from `xmldom`, I just wanted to have a mechanism that allows for convenient traversal of the DOM tree; I think having such tools will reduce boilerplate when the `trias-client` code grows. The `htmlparser2`/`domhandler`/`domutils`/`css-select` allows this, and is well-maintained and fully TypeScript-based.
- 1637d2d Just fixed the `trias:` namespace stripping in a more reliable way by hooking into the parser.

### CODE REVIEW

**Comment by andaryjo** [comment]
Hi @derhuerst, thank you so much for contributing! 

If you weren't able to tell by now, this is my first TypeScript project and it might be a bit unpolished. I therefore welcome any changes that help building a better codebase. 🚀 

It might take me a while to review all of this, but keeping it all in this PR should work fine. Just let me know you're finshed and mark this PR as ready so I can then start looking into it.

**Comment by derhuerst** [comment]
The PR is ready to review code-wise, I just wasn't sure you want all changes in *one*.

I will submit further contributions in follow-up PRs.

**Comment by andaryjo** [comment]
As this PR is massive, I'm merging this into the branch `derhuerst-tweaks` to be able to do some testing and maybe modifications. I'll create a new PR from there.

**Comment by andaryjo** [comment]
Moved it here: https://github.com/andaryjo/trias-client/pull/19

**Pull request merged**
